### ISSUE TITLE
Create One-Pager for Eat, Weigh, Fit App

### ISSUE THREAD

**Issue by mtkfolger** [mtkfolger/EatWeighFit#2]
### **As a user of fitness applications,**
I want a one page document that explains the details of our project, so that anyone interested can read and understand the goals, use-case and deliverables of our application. 

**Given** I am using a fitness, food and weight tracking application, 

**When** I read a one-pager about the _Eat, Weight, Fit_ application,
**Then** I will understand the scope of the project, expected deliverables for this application, and the broad use case of the application

**Comment by austinrohn19** [comment]
i made sure it was a PDF!!!!
